version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: marketplace_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: production
      args:
        DATABASE_URL: postgres://user:password@db:5432/marketplace
    container_name: marketplace_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://user:password@db:5432/marketplace
      NODE_ENV: production
    ports:
      - '3000:3000'
    command: /usr/src/app/docker-entrypoint.sh